import { test, expect } from "@playwright/test";
import { clickDemo } from "./helpers";

test("gates stay visible and editable after scale changes; recommendations recover a poor range", async ({ page }) => {
  const saved: any[] = [];
  page.on("request", (request) => {
    if (request.url().endsWith("/__test_rpc") && request.postDataJSON()?.action === "save") saved.push(request.postDataJSON().project);
  });
  await page.goto("/");
  await clickDemo(page);
  await expect(page.locator(".statistics")).toContainText("16,000");
  await page.getByRole("button", { name: "矩形", exact: true }).click();
  const stage = page.locator(".plot-stage").first();
  const box = (await stage.boundingBox())!;
  await page.mouse.move(box.x + 90, box.y + 100);
  await page.mouse.down();
  await page.mouse.move(box.x + 185, box.y + 185, { steps: 8 });
  await page.mouse.up();
  await expect(page.locator(".statistics tbody tr")).toHaveCount(2);
  const count = await page.locator(".statistics tbody tr").nth(1).locator("td").nth(1).innerText();
  const originalShape = await stage.locator(".gate-shape polygon").getAttribute("points");
  await page.locator('[data-axis-label="x"]').first().click({ button: "right" });
  let dialog = page.getByRole("dialog", { name: "X軸のスケール詳細" });
  await expect(dialog.locator("[data-recommend]")).toBeEnabled();
  await dialog.locator('[name="scale"]').selectOption("log");
  await dialog.getByRole("button", { name: "適用して閉じる" }).click();
  await expect(stage.locator(".gate-shape polygon")).toHaveCount(1);
  await expect(stage.locator("[data-gate-label]")).toContainText("P1");
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await expect(page.locator(".statistics tbody tr").nth(1).locator("td").nth(1)).toHaveText(count);
  expect(await stage.locator(".gate-shape polygon").getAttribute("points")).not.toBe(originalShape);
  await page.locator('[data-tool="select"]').click();
  const handle = (await stage.locator("circle").nth(1).boundingBox())!;
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle.x + handle.width / 2 - 25, handle.y + handle.height / 2 + 20, { steps: 8 });
  await page.mouse.up();
  await expect(page.locator(".statistics tbody tr").nth(1).locator("td").nth(1)).not.toHaveText(count);
  await page.locator("#save").click();
  await expect(page.locator(".status")).toContainText("保存しました");
  expect(saved.at(-1).gates[0].x.scale).toBe("linear");
  expect(saved.at(-1).worksheets[0].plots[0].x.scale).toBe("log");
  await page.locator("#undo").click();
  await expect(page.locator(".statistics tbody tr").nth(1).locator("td").nth(1)).toHaveText(count);
  await page.locator('[data-axis-label="x"]').first().click({ button: "right" });
  dialog = page.getByRole("dialog", { name: "X軸のスケール詳細" });
  await expect(dialog.locator("[data-recommend]")).toBeEnabled();
  await dialog.locator('[name="auto"]').uncheck();
  await dialog.locator('[name="min"]').fill("0");
  await dialog.locator('[name="max"]').fill("100");
  await expect(dialog.locator(".axis-range-warning")).toContainText("集中");
  await dialog.locator("[data-recommend]").click();
  await expect(dialog.locator('[name="scale"]')).toHaveValue("linear");
  await expect(dialog.locator("[data-axis-preview] svg")).toBeVisible();
  await dialog.getByRole("button", { name: "適用して閉じる" }).click();
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await expect(stage.locator(".gate-shape polygon")).toHaveCount(1);
  await expect(page.locator(".statistics tbody tr").nth(1).locator("td").nth(1)).toHaveText(count);
});

test("statistics widgets support selected-group deletion from buttons, context menus and Delete with undo", async ({ page }) => {
  await page.goto("/");
  await clickDemo(page);
  await expect(page.locator(".statistics")).toContainText("16,000");
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await expect(page.locator(".statistics-widget")).toHaveCount(1);
  const add = async () => {
    await page.locator(".widget-add-menu > summary").click();
    await page.locator("#statistics-widget-settings").click();
    await page.getByRole("dialog", { name: "統計ウィジェットの表示項目" }).getByRole("button", { name: "適用", exact: true }).click();
  };
  await add();
  await page.locator("[data-select-widget]").nth(0).check();
  await page.locator("[data-select-widget]").nth(1).check();
  await add();
  await expect(page.locator(".statistics-widget")).toHaveCount(3);
  const keptId = await page.locator(".statistics-widget").last().getAttribute("data-statistics-widget");
  await page.locator("[data-remove-widget]").first().click();
  await expect(page.locator(".statistics-widget")).toHaveCount(1);
  await expect(page.locator(".statistics-widget")).toHaveAttribute("data-statistics-widget", keptId!);
  await page.locator("#undo").click();
  await expect(page.locator(".statistics-widget")).toHaveCount(3);
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await page.locator("[data-select-widget]").first().check();
  await page.locator("[data-select-widget]").last().check();
  await page.locator(".statistics-widget-head").first().click({ button: "right", position: { x: 130, y: 12 } });
  await page.getByRole("menuitem", { name: "選択した2ウィジェットを削除" }).click();
  await expect(page.locator(".statistics-widget")).toHaveCount(1);
  await page.locator("#undo").click();
  await expect(page.locator(".statistics-widget")).toHaveCount(3);
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await page.locator("[data-select-widget]").first().check();
  await page.locator("[data-select-widget]").last().check();
  await page.keyboard.press("Delete");
  await expect(page.locator(".statistics-widget")).toHaveCount(1);
  await expect(page.locator(".plot-card")).toHaveCount(1);
});
