import { test, expect } from "@playwright/test";
import { resolve } from "node:path";
import { clickToolbarAction } from "./helpers";
test("import-time scale and limits can be previewed, cancelled, applied, undone and restored after reload", async ({ page }) => {
  const saved: any[] = [];
  page.on("request", (request) => {
    if (request.url().endsWith("/__test_rpc") && request.postDataJSON()?.action === "save") saved.push(request.postDataJSON().project);
  });
  await page.goto("/");
  await expect(page.locator(".status")).toContainText("起動完了");
  await page.evaluate(async (path) => {
    const call = (payload: any) => (window as any).__TAURI_INTERNALS__.invoke("request", { payload });
    const s = (await call({ action: "demo" })).samples[0];
    const x = { channel: "FITC-A", scale: "logicle", w: .7, t: 262144, m: 4.5, a: 0, min: -.4, max: 4.1, autoRange: false };
    const y = { channel: "SSC-A", scale: "linear", w: .5, t: 262144, m: 4.5, a: 0, min: 0, max: 200000, autoRange: false };
    await call({ action: "save", path, project: { schema: "flowdesk-r/1", name: "Imported axes", samples: [s], gates: [], selectedGate: "root", divaAxisDefaults: [{ ...x, w: .5, max: 5 }], activeWorksheet: "sheet", worksheets: [{ id: "sheet", name: "DIVA", mode: "global", divaSourceId: "original", plots: [{ id: "plot", sampleId: "active", population: [], mode: "scatter", x, y, importedAxes: { x, y }, left: 24, top: 24, width: 440, height: 360 }] }] } });
  }, resolve("artifacts/ui-workspace.json"));
  await clickToolbarAction(page, "#load");
  await expect(page.locator(".status")).toContainText("更新完了");
  const xLabel = page.locator('[data-axis-label="x"]');
  await xLabel.click({ button: "right" });
  let dialog = page.getByRole("dialog", { name: "X軸のスケール詳細" });
  await dialog.locator('[name="scale"]').selectOption("linear");
  await dialog.locator('[name="auto"]').uncheck();
  await dialog.locator('[name="min"]').fill("-200");
  await dialog.locator('[name="max"]').fill("200000");
  await dialog.getByRole("button", { name: "適用して閉じる" }).click();
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await xLabel.click({ button: "right" });
  dialog = page.getByRole("dialog", { name: "X軸のスケール詳細" });
  await dialog.locator("[data-restore-import]").click();
  await expect(dialog.locator('[name="scale"]')).toHaveValue("logicle");
  await expect(dialog.locator('[name="w"]')).toHaveValue("0.7");
  await expect(dialog.locator('[name="min"]')).toHaveValue("-0.4");
  await expect(dialog.locator('[name="max"]')).toHaveValue("4.1");
  await expect(dialog.locator("[data-axis-preview] svg")).toBeVisible();
  await dialog.getByRole("button", { name: "キャンセル" }).click();
  await xLabel.click({ button: "right" });
  await expect(dialog.locator('[name="scale"]')).toHaveValue("linear");
  await dialog.locator("[data-restore-import]").click();
  await dialog.getByRole("button", { name: "適用して閉じる" }).click();
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await page.locator("#save").click();
  await expect(page.locator(".status")).toContainText("保存しました");
  expect(saved.at(-1).worksheets[0].plots[0].x).toMatchObject({ scale: "logicle", w: .7, min: -.4, max: 4.1 });
  await page.locator("#undo").click();
  await expect(page.locator(".status")).not.toHaveClass(/pending/);
  await xLabel.click({ button: "right" });
  await expect(dialog.locator('[name="scale"]')).toHaveValue("linear");
  await dialog.getByRole("button", { name: "キャンセル" }).click();
  await clickToolbarAction(page, "#load");
  await expect(page.locator(".status")).toContainText("更新完了");
  await xLabel.click({ button: "right" });
  await expect(dialog.locator('[name="w"]')).toHaveValue("0.7");
  await expect(dialog.locator('[name="max"]')).toHaveValue("4.1");
});
