if (.Platform$OS.type == "windows") invisible(Sys.setlocale("LC_CTYPE", "English_United States.utf8"))
source("r/core.R", encoding = "UTF-8")
suppressPackageStartupMessages(library(jsonlite))
passed <- 0L
test <- function(name, code) { force(code); passed <<- passed + 1L; cat("PASS", name, "\n") }
errors <- function(code, pattern) { e <- tryCatch({force(code); NULL},error = identity); stopifnot(inherits(e,"error"),grepl(pattern,conditionMessage(e))) }
storage <- tempfile(); dir.create(storage)
ch <- c("FITC-A","PE-A","APC-A")
truth <- matrix(c(-50, 20, 100, 400, -25, 70, 3000, 900, -100),3,byrow=TRUE,dimnames=list(NULL,ch))
spill <- matrix(c(1,.13,.02,.025,1,.07,.01,.035,1),3,byrow=TRUE,dimnames=list(ch,ch))
observed <- truth %*% spill
config <- list(enabled=TRUE, channels=as.list(ch),values=rows(spill))
test("asymmetric compensation and preserved negatives", {actual <- exprs(apply_compensation(flowFrame(observed),config));stopifnot(max(abs(actual-truth))<1e-4,actual[1,1]<0)})
test("detector order mapping", {actual <- exprs(apply_compensation(flowFrame(observed[,c(3,1,2)]),config));stopifnot(max(abs(actual[,ch]-truth))<1e-4)})
test("raw frame stays unchanged", {f<-flowFrame(observed);before<-exprs(f);apply_compensation(f,config);stopifnot(identical(exprs(f),before))})
test("singular spill rejected", {bad<-config;bad$values<-rows(matrix(1,3,3));errors(apply_compensation(flowFrame(observed),bad),"singular")})
test("unknown detector rejected", {bad<-config;bad$channels[[1]]<-"wrong";errors(apply_compensation(flowFrame(observed),bad),"detector")})
xy <- cbind(X=c(-1,0,1,2,0),Y=c(-1,0,1,-1,1));f<-flowFrame(xy)
x<-axis_default("X");x$scale<-"linear";y<-axis_default("Y");y$scale<-"linear"
g<-list(id="p",name="P",parent="root",type="rectangle",x=x,y=y,bounds=as.list(c(-.5,1.5,-.5,1.5)))
test("rectangle gate full event count",stopifnot(sum(gate_masks(f,list(g))$p)==3))
test("parent intersection", {child<-g;child$id<-"c";child$parent<-"p";child$bounds<-as.list(c(-10,10,-10,10));stopifnot(identical(gate_masks(f,list(child,g))$c,gate_masks(f,list(g))$p))})
test("cycle rejected",{a<-g;b<-g;a$id<-"a";a$parent<-"b";b$id<-"b";b$parent<-"a";errors(gate_masks(f,list(a,b)),"cycle")})
test("missing parent rejected",{bad<-g;bad$parent<-"missing";errors(gate_masks(f,list(bad)),"Missing parent")})
test("quadrants partition including equality",{gs<-lapply(1:4,function(q)list(id=paste0("q",q),type="quadrant",parent="root",x=x,y=y,center=list(0,0),quadrant=q));m<-gate_masks(f,gs);stopifnot(all(Reduce(`+`,m[-1])==1),m$q2[2])})
test("polygon through flowCore",{poly<-g;poly$type<-"polygon";poly$vertices<-list(list(-.5,-.5),list(1.5,-.5),list(1.5,1.5),list(-.5,1.5));stopifnot(sum(gate_masks(f,list(poly))$p)==3)})
test("logicle monotonic and finite for negatives",{a<-axis_default("FITC-A");v<-axis_values(flowFrame(matrix(c(-100,0,100),ncol=1,dimnames=list(NULL,"FITC-A"))),a);stopifnot(all(is.finite(v)),all(diff(v)>0))})
demo<-dispatch(list(action="demo",storage=storage))
p<-list(schema="flowdesk-r/1",name="Validation demo",samples=demo$samples,gates=list(),selectedGate="root",notes="",importWarnings=demo$warnings)
test("full demo analysis",{a<-analyze(p,"demo-42",storage);stopifnot(a$stats[[1]]$count==16000,length(a$plots)==4,length(a$plots[[1]]$points)==16000)})
test("global gate applies to every sample",{
  second<-demo$samples[[1]];second$id<-"demo-43";q<-p;q$samples<-list(p$samples[[1]],second)
  global<-list(id="global",name="Global cells",sampleId="demo-42",scope="global",parent="root",type="rectangle",x=axis_default("FSC-A"),y=axis_default("SSC-A"),bounds=list(0,1e9,0,1e9));q$gates<-list(global)
  a<-analyze(q,"demo-43",storage);stopifnot(length(a$stats)==2,a$stats[[2]]$id=="global",a$stats[[2]]$count==16000)
})
test("zero parent percentage is null",{g<-list(id="zero",name="Empty",sampleId="demo-42",parent="root",type="rectangle",x=axis_default("FSC-A"),y=axis_default("SSC-A"),bounds=list(-10,-5,-10,-5));child<-g;child$id<-"child";child$parent<-"zero";q<-p;q$gates<-list(g,child);a<-analyze(q,"demo-42",storage);stopifnot(is.null(a$stats[[3]]$percentParent),a$stats[[3]]$count==0)})
path<-file.path(storage,"demo.fcs");write.FCS(demo_frame(),path)
test("flowCore FCS import",{i<-import_samples(list(paths=list(path),storage=storage));stopifnot(i$samples[[1]]$events==16000,identical(unname(vapply(i$samples[[1]]$channels,`[[`,"","id")),unname(colnames(exprs(demo_frame())))));p$samples<-i$samples})
test("project save/load roundtrip",{file<-file.path(storage,"project.json");dispatch(list(action="save",project=p,path=file,storage=storage));restored<-dispatch(list(action="load",path=file,storage=storage));stopifnot(identical(restored$samples[[1]]$md5,p$samples[[1]]$md5))})
test("changed source rejected even with cache",{cat("changed",file=path,append=TRUE);errors(read_frame(p$samples[[1]],storage),"changed")})
test("DIVA XML safely rejects entities",{dir<-file.path(storage,"diva");dir.create(dir);write.FCS(demo_frame(),file.path(dir,"tube.fcs"));writeLines('<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><Experiment name="test"/>',file.path(dir,"export.xml"));i<-import_samples(list(paths=list(dir),storage=storage));stopifnot(length(i$samples)==1,grepl("DTD/entity",i$warnings[[1]]))})
test("DIVA experiment metadata and explicit warning",{dir<-file.path(storage,"diva2");dir.create(dir);write.FCS(demo_frame(),file.path(dir,"tube.fcs"));writeLines('<Experiment name="T cells"><Tube name="One"/></Experiment>',file.path(dir,"export.xml"));i<-import_samples(list(paths=list(dir),storage=storage));stopifnot(i$divaMetadata[[1]]$experiments[[1]]=="T cells",grepl("not restored",i$warnings[[1]]))})
cat(passed,"tests passed\n")
